### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by isreport** [dgiagio/warp#10]
Hello.
Windows version of warp-packer currently does not seem to support proxy as I find it cannot proceed on with downloading warp-runner in my corporate environment.
Could you either add proxy support or give a guidance to use manually downloaded version of warp-runner instead?
Thanks.

**Comment by dgiagio** [comment]
`warp-packer` currently doesn't support proxy, however I [added instructions](https://github.com/dgiagio/warp/blob/master/README.md#faq) to explain how you can download it manually yourself.

**Comment by dgiagio** [comment]
As of v0.3.0 `warp-packer` doesn't need to download the runners anymore as those are built in. Please use the new version. Thanks.
