### ISSUE TITLE
Application cache path should be unique per application version (or hash).

### ISSUE THREAD

**Issue by damianh** [dgiagio/warp#3]
Not sure if this is a big issue but raising so there is a record of a discussion.

Currently, the cache path using the application executable name `prog`:

https://github.com/dgiagio/warp/blob/master/warp-runner/src/main.rs#L32-L38

Could this be problematic if:

- Two applications have the same name
- Two different versions of an app are run.

Possible solution: include a deterministic GUID and `warp-packer` time that is then subsequently used as the cache folder.

**Comment by damianh** [comment]
This may also require some consideration to cleaning up the cache for apps no longer being run. Perhaps extracting to `temp` would be a better place?

**Comment by jzebedee** [comment]
This should be at the top. It's impossible to run an updated version of a warped application because the runner will keep loading from the old cached version.

**Comment by mitchhentges** [comment]
I've written a fix for this [over in my fork here](https://gitlab.com/comms-app/warp/-/commit/b85518962f44090cb5e086e42b631dcf106a6aaa) that you may be interested in cherry-picking.

At pack-time, it does a `sha256` hash of the packed input files, then stores/compares it in `$data_dir/state.bin`.
