### ISSUE TITLE
FYI Warp being considered for Deno executables

### ISSUE THREAD

**Issue by PhilParisot** [dgiagio/warp#54]
https://github.com/denoland/deno/issues/986#issuecomment-628851461

**Comment by peters** [comment]
@PhilParisot Our company maintains a fork of this repository. We have created a [GitHub Workflow](https://github.com/fintermobilityas/warp/blob/develop/.github/workflows/rust.yml) and enabled support for `windows-x86`. It should be relatively easy adding support for additional platforms. The reason why we forked this repository is that `warp` is a dependency of [snapx](https://github.com/fintermobilityas/snapx). PRs will be reviewed :)
