### ISSUE TITLE
Request: Example for usage with node.js

### ISSUE THREAD

**Issue by mattinsler** [dgiagio/warp#6]
Hi! I'd love to use this with node.js. If this is possible (I'm assuming it would be one of the goals by the stub for a Java example, being a similar setup to node), please make an example for this at some point in the future. =-)

**Comment by JeanBaptisteWATENBERG** [comment]
I just created https://github.com/dgiagio/warp/pull/7 to describe those steps

**Comment by dgiagio** [comment]
Your example is good but it assume that node is already installed. To make your app self contained you need to bundle node and its dependencies as well.

I'm working on a guide right now and should have instructions in the next few days for node js.

**Comment by JeanBaptisteWATENBERG** [comment]
Yes indeed this is just bundling node_modules dependencies and still requires node to be able to be executed. Thank you very much for your work, I'm looking forward to read your guide.

**Comment by dgiagio** [comment]
Warp now supports Node.js. Please read the instructions here: https://github.com/dgiagio/warp#quickstart-with-nodejs Make sure you are using the latest released version.
